### ISSUE TITLE
Assignment to read-only properties is not allowed in strict mode

### ISSUE THREAD

**Issue by bennyadam** [bfred-it/object-fit-images#104] opened 2018-02-09 10:23 UTC
When importing this script to my code using the ES6 import notation or when including it as an external script in Angular 5's scripts section, the error mentioned in this issue here still persists: #100 

`Assignment to read-only properties is not allowed in strict mode`

Therefore this is currently not WebPack compliant and causes an error in our Angular application.

I tried the other way of including the script itself in our assets and referencing this in the head of our index.html, which is not causing any error though. 

Specifically, IE is complaining about those reassignments:

```
if (!supportsObjectPosition) {
	HTMLImageElement.prototype.getAttribute = function (name) {
		return nativeGetAttribute.call(getOfiImageMaybe(this, name), name);
	};

	HTMLImageElement.prototype.setAttribute = function (name, value) {
		return nativeSetAttribute.call(getOfiImageMaybe(this, name), name, String(value));
	};
}
``` 

Will try to prepare a sample project to make this reproducible as soon as possible, nevertheless wanted to report this already.

Specifically occurred on IE 11 on Windows 8.1.

**Comment by fregante** [comment] 2018-02-09 11:13
Thanks for the report! I used it in webpack projects before so it should work. I'll wait for the repro

**Comment by bennyadam** [comment] 2018-02-09 12:55
Okay, so far I can just tell that it's obviously not a general issue in conjunction with Angular, as I was able to create a working Plunker here, which also works in IE11:
https://plnkr.co/edit/aP1kVGuFqEvHonFMh5Io?p=preview

Still this Plunker does not integrate WebPack though. Hopefully I'll find some time to create a basic project using WebPack in conjunction with ES6 / TypeScript soon to track down the issue.

Might even be related to specific configurations we have in our project - is anything coming to your mind that has been reported in the past or where you'd think that it might be causing the issue? 
Otherwise I will just approach it step by step though, might just take a couple of days!

**Comment by fregante** [comment] 2018-02-09 14:36
Is it possible that it's being bundled twice?

**Comment by aminta** [comment] 2018-05-19 11:51
Hi! Almost the same problem on Safari 9.0, using Webpack:

```
import objectFitImages from 'object-fit-images;

$(document).ready(function() {
    objectFitImages();
});
```

I get the error:

`TypeError: Attempted to assign to readonly property.`

Highlighting this code:

`HTMLImageElement.prototype.getAttribute = function (name) {`

Including objectFitImages with `<script src=https://cdnjs.cloudflare.com/ajax/libs/object-fit-images/3.2.3/ofi.min.js></script>` works.

**Comment by fregante** [comment] 2018-05-19 12:25
Uhm... is it in Webpack or via `script` tag? Is the error caused by OFI being loaded twice?

**Comment by aminta** [comment] 2018-05-26 10:19
I've got the error if I use Webpack...

**Comment by seybsen** [comment] 2018-09-27 10:08
> Assignment to read-only properties is not allowed in strict mode

.. means that [strict mode is enabled for OFI](https://github.com/bfred-it/object-fit-images/blob/master/dist/ofi.js#L3), but [this line](https://github.com/bfred-it/object-fit-images/blob/master/dist/ofi.js#L171) is not allowed in strict mode in IE11.

I solved it using the [remove-strict-webpack-plugin](https://www.npmjs.com/package/remove-strict-webpack-plugin) to completely disable `'use strict;'` for my bundle.

**Comment by StephanGerbeth** [comment] 2018-10-28 09:15
I don't wanna use remove-strict-webpack-plugin.

> This module should not be used in production environment. You should fix your strict errors not disable strict mode.

Is it possible to disable `use strict` only in the common.js build?

**Comment by fregante** [comment] 2018-11-10 09:59
The demo works fine with that line in IE11 and all supported browsers, so the issue shouldn't be _strictly_ that line.

To remove it I'd have to re-write the bundling so sadly I can't do that.

I'd say just make sure you're not bundling/loading it twice, somehow, because it's been tested in IE11 and with webpack.

Search "OFI" in your JS or in your developer console (to see ALL the files loaded) 

or just load the file from the CDN if required.

or get pull the built file into your repo and change it. OFI isn't likely to receive any more updates and it's essentially required by only 3% of stubborn users at this point.

**Comment by christopherdarling** [comment] 2019-10-29 16:06
I've experienced the same issue here, it turned out to be caused by an HTMLPictureElement polyfill script being loaded before OFI. Removing that did the trick for me.

**Comment by fregante** [comment] 2019-10-29 16:20
Bingo! That's it. The (small) _notes_ link in the repo mentions that **`picturefill` has to be loaded *after* OFI.** I hope that fixes it for everyone. 

A long time ago I tried fixing that issue in `picturefill`  but the PR was rejected 🤷‍♂️

**Closed as completed by fregante** 2019-10-29 16:20 UTC

**Comment by tremby** [comment] 2019-12-10 06:52
I am loading mine conditionally on tests for the features, asynchronously. That led to a race condition if both polyfills were going to load. I made picturefill wait for a promise before trying to load -- a promise for object-fit-images to be loaded if required, or otherwise an immediately-resolved promise -- and this fixed the problem for me.

**Comment by pgangwani** [comment] 2020-03-31 06:17
This thread saved one day
