### ISSUE TITLE
Unable to include into existing uglified/minified code.

### ISSUE THREAD

**Issue by patricknelson** [bfred-it/object-fit-images#36] opened 2016-09-13 21:50 UTC
I found a workaround for this (just to take the edge off after seeing that subject :+1:). Basically my workflow is this:
- Grunt to compile SASS + JS files
- JS is minified/uglified (etc) into two main files: `head.js` and `foot.js`

My main issue here is that I have one main processor for `head.js` which manually selects a few files here and there and then concatenates/uglifies a few more and so on, until I have my final header file. I noticed that when I included the existing `ofi.browser.js` file, it failed with JS errors in the targeted browser (IE).  This is because IE couldn't handle this file being mangled 2x's.

However, if I disabled the mangling happening by `uglify` here (https://github.com/bfred-it/npm-bundler/blob/master/index.js#L60) I ended up with a file I could simply add to my existing project without adding another completely separate step in my already complex workflow just to accommodate one file which cannot handle being uglified 2x's.

My fix would likely be:
1. Add the option to disable `uglify` in  `bfred-npm-bundler`
2. Use this new option in `object-fit-images` and include a command to build a second version of the file which is not minified (or some workflow which first generates a regular version, then a second uglified version in one command).

What do you think? This would work well for me in the long term since then I can get updates to this module without much hassle (i.e. manually editing your custom packager to disable uglify) and still not have a dramatically modified Grunt workflow.

**Comment by fregante** [comment] 2016-09-14 04:29
As explained in https://github.com/bfred-it/object-fit-images/issues/33 I won't add an unminified version. I tried uglifying OFI.browser.js twice just now and the output is unchanged (i.e. no IE issues are introduced). So the issue is rather in your concatenation process. 

I always suggest moving to a proper dependency bundler like browserify or webpack instead of rawly concatenating files.

**Closed as completed by fregante** 2016-09-14 04:29 UTC

**Comment by patricknelson** [comment] 2016-09-14 20:18
Interesting. I think you're right.

I know it doesn't matter now, but I can tell now after some more in-depth analysis it's definitely an issue with running it through two different minifiers (or at least some issue specifically with `grunt-uglify`). I got to the point to where I noticed that name of the `getStyle` function (converted to a closure) was being overwritten with instead with a minifier optimized/generated check for the return value of `el[ಠ].parsingSrcset` ... doesn't matter now, not worth the time :joy:

**Comment by fregante** [comment] 2016-10-21 12:24
This issue was fixed in UglifyJS 2.7.0

**Comment by the-felis-leo** [comment] 2016-12-14 19:46
Sorry, but I've encourred same/similar problem, with Jalios JCMS.
I can't change/correct this product, so I've rebuild an unminified version...

The problem seems coming from a name conflict.
In fact, the erreur is about that following code: (more specifically on 't')
 
      function t(t) { ....}
      function e(e,i){ .... var s=t(e); ... }
 
After minification, the definition and the call to the function t() have two distinct names.


Futermore, an unobfuscated distribution could help to debug.
Whatever, thank a lot for your work !

**Comment by fregante** [comment] 2016-12-15 01:20
I'd suggest you open an issue for `jcms` because if this is **removing a function** here, it might be removing functions elsewhere too. This is a bug in `jcms`. Minified JavaScript is still normal JavaScript.

---

If you need it unminified, you can run this and generate it locally:

```sh
git clone git@github.com:bfred-it/object-fit-images.git
cd object-fit-images
npm install
sed -i -e "s/('rollup-plugin-uglify/=>('/" */bfred-npm-bundler/*
npm run build
```

And the unminified file will be in `object-fit-images/dist/ofi.browser.js`

Alternatively, switch to a proper bundling system based on modules (browserify, rollup, webpack, ...) and you'll find the unminified version on npm.

**Comment by the-felis-leo** [comment] 2016-12-15 11:22
That's what I've done to  "rebuild an unminified version..." ;-)

**Comment by patricknelson** [comment] 2016-12-15 11:27
Interestingly a common enough issue that now several of us have had to do the same work and bothered to comment on it 😞

**Comment by fregante** [comment] 2017-02-06 12:14
Non-minified version is now in v3 ;)

https://github.com/bfred-it/object-fit-images/blob/master/dist/ofi.js
