### ISSUE TITLE
Media Query images using `<source>` tag not working

### ISSUE THREAD

**Issue by csantos1113** [bfred-it/object-fit-images#103] opened 2018-01-30 20:26 UTC
As you know, there is a technique to render one image or another one with media queries from html.
```
<picture>
    <source media="(min-width: 768px)" srcset="image-large.png"/>
    <img class="imgs" src="small.png"/>
</picture>
```

but the result of using this polyfill `window.objectFitImages( 'img.imgs', { watchMQ: true } )` is always giving me this inline style:

```
background-image: url("small.png");
background-position-x: center;
background-position-y: center;
background-repeat: no-repeat;
background-origin: content-box;
background-size: cover;
```

How can I change the source dynamically?

**Comment by csantos1113** [comment] 2018-01-30 20:35
related to #85

**Comment by fregante** [comment] 2018-01-31 02:22
`picture` is not supported. Duplicate of #3

**Closed as completed by fregante** 2018-01-31 02:22 UTC
